### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Nancy-0714#1]
[Infografía_Nancy_Olivera.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Nancy-0714/files/14640608/Infografia_Nancy_Olivera.pdf)

**Comment by IrvinSanchez-dev** [comment]
La calificacion obtenida mediante la rubrica es de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
